name       : perl-anyevent
version    : 7.14
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/AnyEvent-7.14.tar.gz : 539358d225bad34b4a64f5217f8c2a707b15e3a28c74120c9dd2270c7cca7d2a
license    : MIT
component  : programming.perl
summary    : Perl AnyEvent is an event loop framework
description: |
    Perl AnyEvent is an event loop framework
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
