name       : perl-anyevent
version    : '7.17'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/AnyEvent-7.17.tar.gz : 50beea689c098fe4aaeb83806c40b9fe7f946d5769acf99f849f099091a4b985
homepage   : https://metacpan.org/pod/AnyEvent
license    : MIT
component  : programming.perl
summary    : Perl AnyEvent is an event loop framework
description: |
    Perl AnyEvent is an event loop framework
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
